### ISSUE TITLE
why copy..

### ISSUE THREAD

**Issue by Bakersbakebread** [mrTownsend/BeeHive-AutoMod#1]

**Comment by mrTownsend** [comment]
Hey bread. So, obviously, you didn't read the general readme on the repository. Let's go over this. 

2 different things are happening here. 

I adopted the cogs you see under this repo as projects of my own. These are all things I intend to rewrite progressively over time to serve my direct needs. You did an amazing job of making the core cog, yes, but it doesn't do what *I* want it to do. As part of normalizing all of my project folders, the various authors and version numbers were all set to the same things - mrTownsend, and 0.0.1 respectively as its the first iteration of *my* changes to it. During the process of me actually pulling these cogs, I pulled the folders only, and not the folder OVER IT that contains the README.md, LICENSE, etc etc. Solely the cog folders were pulled. Throughout today multiple developers have reached out to me to rectify it and I've been more than happy to do so for them. Assuming you're interested in the same thing and you didn't just open an issue on my GitHub to tell me to have a good morning, I'll modify the `info.json` and add the LICENSE file respectively, *manually*, from your original repository. 

If there's anything else I can help you with, please let me know. I'll update and close this issue once I've made changes. 

//C

**Comment by mrTownsend** [comment]
LICENSE added. Thanks for reaching out.
